### ISSUE TITLE
Code updating 

### ISSUE THREAD

**Issue by WangYitian123** [kaist-amsg/LocalRetro#1]
Hi,

Thanks for your excellent work. I noticed that part of your code is being updated.

Looking forward for your updating.

**Comment by shuan4638** [comment]
@WangYitian123 Thanks for the comment. We are now working on cleaning the codes as well as the code for forward synthesis prediction. We will update the code again once the work is done!

**Comment by shuan4638** [comment]
The code is updated on 2022.02.09.
