### ISSUE TITLE
Why check changed atoms between product and reactants for test data during preprocessing?

### ISSUE THREAD

**Issue by mxc19912008** [kaist-amsg/LocalRetro#11]
Hi, 

Correct me if I didn't see it correctly.

During preprocessing, training, validation and test data have all been put through the [extractor](https://github.com/kaist-amsg/LocalRetro/blob/d98ecd98dc68ad6685b58021c9fc37d5d5b97d16/preprocessing/Run_preprocessing.py#L233), and when using the extractor, you compare the differences between product and reactants [here](https://github.com/kaist-amsg/LocalRetro/blob/d98ecd98dc68ad6685b58021c9fc37d5d5b97d16/LocalTemplate/template_extractor.py#L558).

It's totally okay to check the differences between product and reactants for training data, but I don't understand why you need to check the differences between product and reactants for test data.

**Comment by shuan4638** [comment]
Hi,

You are correct, I do see the difference between product and reactants for test data as well. We did this mainly to check the coverage of our proposed local reaction template, i.e., the theoretical upper bound of the prediction accuracy.
It's totally fine if you don't check the difference between product and reactants and you can still get the same results.
