### ISSUE TITLE
How to extract template and retrosynthesis from scratch

### ISSUE THREAD

**Issue by sitanshubhunia** [kaist-amsg/LocalRetro#14]
Respected Sir,
Thanks for this valuable repo. Requesting you to guide how I start from scratch for a given set of reaction smiles ->extract template -> retrosynthesis. If possible please guide me with steps. I am not from a chemistry background just simple a technical guy.

Regards,
Sitanshu

**Comment by shuan4638** [comment]
Going through the [demo noteboook](https://github.com/kaist-amsg/LocalRetro/blob/main/Retrosynthesis.ipynb) should be helpful to understand how to use it. Let me know if you need further help.

**Comment by sitanshubhunia** [comment]
Thanks Sir for your reply. Trying to create virtual environment on windows 10, but stuck on "conda install -c conda-forge rdkit -y"
For ref. I have attached screen shot.
 
![Stuck](https://user-images.githubusercontent.com/840684/231954034-ddb3e134-3113-4043-81a7-997461c36b4f.png)

**Comment by shuan4638** [comment]
Did you try `pip install rdkit`?

**Comment by sitanshubhunia** [comment]
**Again thanks Sir**. Now virtual env. is created. 

![Working](https://user-images.githubusercontent.com/840684/231968647-28ac6a32-a33b-4d10-8a5e-a6df8b797eaf.png)

Let me try to other steps

**Comment by sitanshubhunia** [comment]
Sorry to disturb you again and again. I admitted that due to lack of my knowledge I am getting this error.
If possible please help me for further steps.


![issue](https://user-images.githubusercontent.com/840684/231979253-b5823cb0-b8a8-46c9-9965-f4e152d524b3.png)

**Comment by shuan4638** [comment]
Did you install dgl package in the same envinroment?

**Comment by sitanshubhunia** [comment]
Yes sir. 
FYI I have attached screen shots. Obviously I am doing something wrong. But not figure it out where .......

**dgl**
----  
![dgl](https://user-images.githubusercontent.com/840684/232023236-c4d3467f-3d5a-4b2e-8915-8aa565bedc02.png)

**dgllife**

![dgllife](https://user-images.githubusercontent.com/840684/232023429-215da956-f969-4ef9-b654-819e13fbe22b.png)

**ipynb**

![ipyhton-run](https://user-images.githubusercontent.com/840684/232023519-8aeb84bb-006c-46a8-b046-874a6b9261d7.png)

### The list of commands

conda create -c conda-forge -n rdenvNew python=3.7 -y
conda activate rdenvNew
conda install pytorch cudatoolkit=10.2 -c pytorch -y
**pip install rdkit**  _[ as per your advice and successfully installed]_ 
pip install dgl
pip install dgllife

**Comment by shuan4638** [comment]
Can you make sure the Jupiter notebook you are running is using the same virtual environment you install those packages?

**Comment by sitanshubhunia** [comment]
Thanks Sir. 
I have to add two more pip install 
1. pip install jupyter
2. pip install torch

jupyter is now running from same env.

![yes](https://user-images.githubusercontent.com/840684/232234723-c930b226-2d9c-410a-9915-27dc5be3084b.png)

**### After that I am getting following** 

![error](https://user-images.githubusercontent.com/840684/232234788-f92745bf-3548-4226-a520-3806fd63cc1f.png)

After change 
device = torch.device('cpu')

I am getting following error
![cuda](https://user-images.githubusercontent.com/840684/232235311-2e6b1f8f-3b39-4eb2-b876-d23db9b3ea9a.png)


My Environment is Windows 11 Pro

Directory structure
 

![dirstructure](https://user-images.githubusercontent.com/840684/232235540-7581c1dd-84d5-4f12-b67b-c2022a6e604e.png)

**Comment by shuan4638** [comment]
@sitanshubhunia Did you solve the problem?

**Comment by sitanshubhunia** [comment]
No  @shuan4638  Sir. I am unable to solve it. 

I am also stuck in step 3 
[3] Train LocalRetro model

![train](https://user-images.githubusercontent.com/840684/233259995-dff413cb-9a8a-4764-8049-3c92239dcc60.png)

**### Stuck in this step. Nothing is saved in model folder.**

![stuck](https://user-images.githubusercontent.com/840684/233260095-bb690111-5a9f-4373-95bb-11936914a47b.png)

**Comment by shuan4638** [comment]
@sitanshubhunia 
The training process takes time, you may see the model file after the first epoch.
You'll be able to use the python notebook once you obtain the model file.

**Comment by sitanshubhunia** [comment]
@shuan4638 Sir thanks for reply. Yes it's running. 
Still now ....
![image](https://user-images.githubusercontent.com/840684/233270608-ddaaf519-5829-41de-bd9d-2f4df1315ca1.png)

I hope, I can run this after all steps done...

**Comment by sitanshubhunia** [comment]
@shuan4638 Sir, Finally I have successfully run **Retrosynthesis.ipynb**.

Requesting you to give the steps how to proceed, if I have only reaction smiles then how I able to use this model extract templates , generate other files and retrosynthesis. 

I understand that this type of questions  may be annoying to you.

**This is not an issue. Just questions**🙏

Thanks for your valuable works.

**Comment by shuan4638** [comment]
LocalRetro is not the model to generate reaction template. Reaction template can be directly generated by the `extract_from_reaction` function defined [here](https://github.com/kaist-amsg/LocalRetro/blob/main/LocalTemplate/template_extractor.py). Playing with this function should be helpful.
