### ISSUE TITLE
why not set use_symbol: False by default when extract retro template?

### ISSUE THREAD

**Issue by queliyong** [kaist-amsg/LocalRetro#18]
Hi，
I note that when set use_symbol: False ,the templates extracted are more general, and the number of templates are much smaller, can this setting help improve the prediction performance? But the default setting is "use_symbol: True", is there any reason that you did not use the more general templates? Thanks.

**Comment by shuan4638** [comment]
I tried to set the `use_symbol` flag to True before and trained LocalRetro with these general templates, the the performance actually decreased by certain reasons. So I eventually set it to True and that is what I described in the JACS Au paper.

I believe there should be some ways to adopt these general templates on LocalRetro with some proper changes in model architecture or other technics. It's a good idea to test it out.

**Comment by queliyong** [comment]
Thanks a lot.
