### ISSUE TITLE
NameError: name 'LocalRetro' is not defined

### ISSUE THREAD

**Issue by wiemta** [kaist-amsg/LocalRetro#6]
![er](https://user-images.githubusercontent.com/69146370/164451093-34ee6188-f12d-47f1-93a0-019825a61609.PNG)

**Comment by shuan4638** [comment]
@wiemta Hi, can you check you have the line `from models import LocalRetro` in scripts/utils? It seems that LocalRetro is not imported before you run the function.

**Comment by wiemta** [comment]
ok thanks , but i have another erreurs

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-12-e500164480f2>](https://localhost:8080/#) in <module>()
      1 args = {'data_dir': data_dir, 'model_path': model_path, 'config_path': config_path, 'device': device}
----> 2 model, graph_function, atom_templates, bond_templates, template_infos = init_LocalRetro(args)

4 frames
[/content/gdrive/MyDrive/monstage/LocalRetro/Retrosynthesis.py](https://localhost:8080/#) in init_LocalRetro(args)
     38     args['mode'] = 'test'
     39     args = init_featurizer(args)
---> 40     model = load_model(args)
     41     atom_templates, bond_templates, template_infos = load_templates(args)
     42     smiles_to_graph = partial(smiles_to_bigraph, add_self_loop=True)

[/content/gdrive/MyDrive/monstage/LocalRetro/scripts/utils.py](https://localhost:8080/#) in load_model(args)
    116 
    117     else:
--> 118         model.load_state_dict(torch.load(args['model_path'])['model_state_dict'])
    119         return model
    120 

[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in load(f, map_location, pickle_module, **pickle_load_args)
    592         pickle_load_args['encoding'] = 'utf-8'
    593 
--> 594     with _open_file_like(f, 'rb') as opened_file:
    595         if _is_zipfile(opened_file):
    596             # The zipfile reader is going to advance the current file position.

[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in _open_file_like(name_or_buffer, mode)
    228 def _open_file_like(name_or_buffer, mode):
    229     if _is_path(name_or_buffer):
--> 230         return _open_file(name_or_buffer, mode)
    231     else:
    232         if 'w' in mode:

[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'models/LocalRetro_USPTO_MIT.pth'
