### ISSUE TITLE
How to use the trained model to predict the custom dataset?

### ISSUE THREAD

**Issue by youcefBouraoui** [kaist-amsg/LocalRetro#8]
Hi, Thanks for sharing your excellent work.

Recently I trained the model.
After that, I want to predict one entry SMILES product to see how the model really performs.
So, I have the product smile. (Just like this  O=C(N1)NN=C(C2=CC=C(C(F)(F)F)C=C2OC)C1=O), 
and I want to know how to configure the data stream, to use the trained models, and have a predicted result.

Thanks in advance

**Comment by shuan4638** [comment]
You can go to the Retrosynthesis.ipynb file and change the dataset in cell #2 and the smiles in cell #4.

**Comment by youcefBouraoui** [comment]
So if i get you rigth after running Retrosynthesis.ipynb wit my own data it will give me the reactants that produce the product input ?

**Comment by shuan4638** [comment]
Exactly. Let me know if you need more help with that.

**Comment by youcefBouraoui** [comment]
OK thank you for your answer, one last question, can this model be template free, meaning can it predict without using templates, because i don't have a solid background in organic chemistry, and without knowing how to extract this templates i find it hard to make improvements if they exist.

**Comment by shuan4638** [comment]
This model itself is a template-based method, meaning that the model cannot work without predefined template. 
The reaction templates are acutally good for human to interpret the prediction result, as I mentioned in the publication. The template extraction method can be found in LocalTemplate directory.
If you still wish to use template-free method, I suggest you to read [this](https://arxiv.org/pdf/2203.11444.pdf) recently published paper which I found incredible.
