### ISSUE TITLE
How to understand the difference of USPTO-MIT performance

### ISSUE THREAD

**Issue by funtion** [kaist-amsg/LocalRetro#9]
Dear Authors,

I'm impressed by the performance on USPTO-50K dataset. However, the top-1 accuracy of USPT-MIT is just 54.1, which is much lower than other papers (i.e., 80 or even 90 accuracy). May I know how to understand the differences? e.g., do you use different data processing or evaluation methods?

Ref: https://www.nature.com/articles/s41467-020-19266-y/tables/4

**Comment by shuan4638** [comment]
I think you are talking about the accuracy of forward synthesis, while this model is a retrosynthesis prediction model. You can not really compare those two results.

**Comment by funtion** [comment]
Oh, I see. Thank you for the clarification.

For USPTO-MIT, is there any other baselines' performance on the retrosynthesis direction available?

**Comment by shuan4638** [comment]
You can see this paper:
https://arxiv.org/pdf/2203.11444.pdf
